name: fire
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - deepdish
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scipy
  - scikit-learn
  - ipykernel
  - ipywidgets
  - notebook
  - jupyterlab
  - pip
  - pip:
    - e2cnn
    - geemap
    - earthengine-api
    - torch
    - torchvision
    - tensorflow
    - tfrecord